### ISSUE TITLE
NullPointerException in GitLabCommitStatusStep

### ISSUE THREAD

**Issue by nussera** [jenkinsci/gitlab-plugin#1030]
This bug seems to be similar to #1024 and #814 but I'm not sure if it is a duplicate.
### Context
- **Gitlab plugin version**: 1.5.13
- **Gitlab version**:  12.8.1-ee 
- **Jenkins version**: 2.222
- **Job type**: Pipeline

### Logs & Traces
```
[Pipeline] End of Pipeline
java.lang.NullPointerException
	at com.dabsquared.gitlabjenkins.workflow.GitLabCommitStatusStep.access$400(GitLabCommitStatusStep.java:34)
	at com.dabsquared.gitlabjenkins.workflow.GitLabCommitStatusStep$GitLabCommitStatusStepExecution$1.onFailure(GitLabCommitStatusStep.java:110)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$FailureAdapter.receive(CpsBodyExecution.java:361)
	at com.cloudbees.groovy.cps.impl.ThrowBlock$1.receive(ThrowBlock.java:68)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

### Problem description

I was forced to delete all old builds (thx 'build discarder').  Now it looks like the error appears in every builds where there is no previous build (anymore).
What makes it worse than a regular failed build, is that Jenkins can't handle the error and would not remove the job from the executor. I had to manually "cancel" at least some of these failed builds.

**Comment by ipleten** [comment]
We have a user 'input' without timeout and that happens each time "Proceed" is pressed after Jenkins restart.

**Comment by ipleten** [comment]
Could it be caused by 'transient' in https://github.com/jenkinsci/gitlab-plugin/blob/1bf706bc807051da7fc4e0843bf4e306888ff743/src/main/java/com/dabsquared/gitlabjenkins/workflow/GitLabCommitStatusStep.java#L77?

**Comment by floryut** [comment]
> We have a user 'input' without timeout and that happens each time "Proceed" is pressed after Jenkins restart.

It looks like we are in the exact same workflow, we also encounter this issue after a Jenkins restart when someone tries to proceed a job awaiting validation.

@ipleten Did you manage to fix this on your end without merging MR #1057 ? Or was the MR closed for another reason ?

**Comment by zOthix** [comment]
I am having the same issue, any one solved it yet?

**Comment by floryut** [comment]
> I am having the same issue, any one solved it yet?

Sorry to say that we "resolved" this by re-coding the entire jenkins->gitlab flow using a groovy shared lib..

**Comment by HeikoBoettger** [comment]
Hi,
I just saw the same issue on our system after having to restart jenkins. Some of the builds were resumed and crashed with the exception mentioned. The ugly thing is that those builds were in failed state but did not get removed from the executor slot for any reason.

I am not into the serialization system of jenkins but I wonder what happens if deserialization of a field fail. Is it possible that it becomes null in case of incompletely written status files?

**Comment by doc-olliday** [comment]
Hi,
we encounter the same issue since a couple of weeks ago. I can't say anymore what change was done on the system, when this error starts to occur - maybe Jenkins core update and/or plugin(s) update.
Any ideas to solve this would be great.

**Comment by krisstern** [comment]
Hi @doc-olliday Let me see if I could open a PR after the closed #1057, or seek another way to approach this issue over the next few days.

**Comment by krisstern** [comment]
I have just checked that the current SNAPSHOT already contains a similar fix in #1057, so let me cut a new release of the plugin manually now.

**Comment by krisstern** [comment]
Closing this issue as the problem should have been fixed with Release 1.7.

**Comment by doc-olliday** [comment]
I've updated to version 1.7.1
But unfortunately the problem is still present. It occurs when a pipeline is running and in the meanwhile the Jenkins server node is restarted. The pipeline is proceeded and ends with the following stacktrace:

`java.lang.NullPointerException
	at com.dabsquared.gitlabjenkins.workflow.GitLabCommitStatusStep$GitLabCommitStatusStepExecution$1.onSuccess(GitLabCommitStatusStep.java:103)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$SuccessAdapter.receive(CpsBodyExecution.java:371)
	at com.cloudbees.groovy.cps.Outcome.resumeFrom(Outcome.java:70)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:149)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:146)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:146)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:420)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0(ErrorLoggingExecutorService.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by krisstern** [comment]
@doc-olliday Let me do a bit "digging" over the weekend and let you know if we can find a fix shortly. May need you to help with testing though if you don't mind.

**Comment by krisstern** [comment]
Found the bug, am working on a fix now

**Comment by doc-olliday** [comment]
@krisstern many thanks to you for the fast response!
I'll try to help with testing, if I can.

**Comment by krisstern** [comment]
You are welcome @doc-olliday! In fact I have just submitted a PR #1395 for this issue. Will you need me to cut a new release before you can test it, or are you cool testing off the PR?

**Comment by krisstern** [comment]
Have been debating whether to use `t.getMessage()` or `t.toString()` where `t` is the throwable for the additional check, but will find out if I am on the right track only after some testing is done.

**Comment by krisstern** [comment]
Hi @doc-olliday I have just cut a new release [gitlab-plugin-1.7.2](https://github.com/jenkinsci/gitlab-plugin/releases/tag/gitlab-plugin-1.7.2) with the patch to fix this bug. Please test it out and let me know if it works. If not, there is still one more change I can make to see if we can resolve this. Appreciate any help possible!

**Comment by doc-olliday** [comment]
@krisstern the problem still exists.
Here my stacktrace:
`java.lang.NullPointerException
	at com.dabsquared.gitlabjenkins.workflow.GitLabCommitStatusStep$GitLabCommitStatusStepExecution$1.onSuccess(GitLabCommitStatusStep.java:103)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$SuccessAdapter.receive(CpsBodyExecution.java:371)
	at com.cloudbees.groovy.cps.Outcome.resumeFrom(Outcome.java:70)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:149)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:146)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:146)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:420)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0(ErrorLoggingExecutorService.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Finished: FAILURE
`

I've created a very simple pipeline to test around a little bit. It looks like:

```
pipeline {
  agent any
  options {
    gitLabConnection('My GitLab')
    gitlabBuilds(builds: ['Hello', 'World', 'Bravo'])
  }
  stages {
    stage('Hello') {
      steps {
        gitlabCommitStatus(env.STAGE_NAME) {
          sh 'env|sort'
          sh 'sleep 10'
        }
      }
    }
    stage('World') {
      steps {
        gitlabCommitStatus(env.STAGE_NAME) {
          sh 'env|sort'
          sh 'sleep 120'
        }
      }
    }
    stage('Bravo') {
      steps {
        gitlabCommitStatus(env.STAGE_NAME) {
          sh 'env|sort'
          sh 'sleep 10'
        }
      }
    }
  }
}
```
In the stage `World` there is a `sleep 120` to give time to restart the Jenkins server.

1. Commenting all `gitlabCommitStatus()` in all stages and `gitlabBuilds()` the pipeline is green after resuming from a restart.
2. Having `gitlabBuilds()` enabled (without any `gitlabCommitStatus()`) the pipeline fails with the mentioned stacktrace after resuming.
3. Commenting `gitlabBuilds()` out and enabling `gitlabCommitStatus()` in stages `Hello` and `Bravo` the pipeline is green after resuming from restart. `Hello` stage runs before restart; `Bravo` runs after restart; `Wold` is the stage where the restart occurs.
4. Enabling `gitlabCommitStatus()` in stage `World` the pipeline fails with the stacktrace.

**Comment by krisstern** [comment]
Thanks @doc-olliday Let me try to come up with a patch by TDD using the test case you have provided! Appreciate it

**Comment by krisstern** [comment]
Looks like there were more than one bug, as the previous one was from the `onFailure()` method, now it is from `onSuccess()` in `src/main/java/com/dabsquared/gitlabjenkins/workflow/GitLabCommitStatusStep.java`'s `start()`.

**Comment by krisstern** [comment]
Hi @doc-olliday I have made a patch which has been tested using the pipeline script you have provided and the build was successful:

```shell
pipeline {
  agent any
  options {
    gitLabConnection('My GitLab')
    gitlabBuilds(builds: ['Hello', 'World', 'Bravo'])
  }
  stages {
    stage('Hello') {
      steps {
        gitlabCommitStatus(env.STAGE_NAME) {
          sh 'env|sort'
          sh 'sleep 10'
        }
      }
    }
    stage('World') {
      steps {
        gitlabCommitStatus(env.STAGE_NAME) {
          sh 'env|sort'
          sh 'sleep 120'
        }
      }
    }
    stage('Bravo') {
      steps {
        gitlabCommitStatus(env.STAGE_NAME) {
          sh 'env|sort'
          sh 'sleep 10'
        }
      }
    }
  }
}
```
Please see if the new patch works for you as well.

**Comment by doc-olliday** [comment]
Hi @krisstern,
still no success. Maybe there's something wrong with my Jenkins installation?
Here again the stacktrace, the pipeline is still the same as above.
```
+ sleep 120
Resuming build at Sun Feb 05 11:16:01 CET 2023 after Jenkins restart
Waiting for reconnection of tchaikowsky before proceeding with build
Ready to run at Sun Feb 05 11:16:02 CET 2023
[Pipeline] }
[Pipeline] End of Pipeline
java.lang.NullPointerException
	at com.dabsquared.gitlabjenkins.workflow.GitLabCommitStatusStep$GitLabCommitStatusStepExecution$1.onSuccess(GitLabCommitStatusStep.java:103)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$SuccessAdapter.receive(CpsBodyExecution.java:371)
	at com.cloudbees.groovy.cps.Outcome.resumeFrom(Outcome.java:70)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:149)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:146)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:146)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:420)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0(ErrorLoggingExecutorService.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Finished: FAILURE
```

**Comment by krisstern** [comment]
No worries @doc-olliday Let me try another approach and see if it works

**Comment by krisstern** [comment]
@doc-olliday Would you like to give the latest patch another try to see if the bug you encountered is still there?: https://github.com/jenkinsci/gitlab-plugin/releases/tag/gitlab-plugin-1.7.4

**Comment by doc-olliday** [comment]
Hi @krisstern,
I've installed 1.7.4 and 1.7.5. In both versions I've got the NullPointerException.

**Comment by krisstern** [comment]
Hi @doc-olliday Let me try one more patch before giving up. My apologies for the bug as it is very hard to test due to the way workflow is being tested.

**Comment by krisstern** [comment]
Hello @doc-olliday I have just made a patch which should fix the NPE bug in version 1.7.6.

**Comment by doc-olliday** [comment]
Hi @krisstern indeed the behaviour has changed now. But the build won't resume after the restart.
That's o.k. for me, because now I can pause the pipeline and then abort it without a NPE. Here a screenshot

![grafik](https://user-images.githubusercontent.com/49946087/219765650-590ee9cd-e432-4401-965c-6fd778a323d3.png)

**Comment by krisstern** [comment]
Hi @doc-olliday That's good to know. It would be great if you could open an issue regarding the cannot resume after restart issue so we can look into it later with new pull requests). If you are not available to do that it would be okay as well.

We are grateful for your feedback!
