### ISSUE TITLE
JCasC compatibility: add support for useAuthenticatedEndpoint 

### ISSUE THREAD

**Issue by Smasherr** [jenkinsci/gitlab-plugin#974]
### Context
- **Gitlab plugin version**: 1.5.12
- **Jenkins version**: 2.194

### Logs & Traces

```
io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig : useAuthenticatedEndpoint.
Available attributes : connections
	at io.jenkins.plugins.casc.BaseConfigurator.handleUnknown(BaseConfigurator.java:377)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:366)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:352)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$7(ConfigurationAsCode.java:709)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:659)
Caused: io.jenkins.plugins.casc.ConfiguratorException: unclassified: error configuring 'unclassified' with class io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:665)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:709)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:694)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:585)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:280)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:272)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1118)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1152)
	at jenkins.model.Jenkins.<init>(Jenkins.java:959)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:250)
```

### Problem description

Using `useAuthenticatedEndpoint` in a CasC-config results in the above stated error. To fix it it is needed to change the visibility of setter `GitLabConnectionConfig#setUseAuthenticatedEndpoint`.

PR: https://github.com/jenkinsci/gitlab-plugin/pull/965

**Comment by dr-zeta** [comment]
do you have an ETA for releasing the 1.5.14 to the Jenkins plugin repo?

**Comment by Smasherr** [comment]
@markyjackson-taulia Are you still willing to work on this issue?

**Comment by theatricshrink** [comment]
As a workaround I'm currenlty using this init groovy script:

//==================================================
//Gitlab Plugin Configuration
//==================================================

import jenkins.model.*
import com.dabsquared.gitlabjenkins.*

def jenkins = Jenkins.getInstance()
def gitLabConfig = jenkins.getDescriptor("com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig")

gitLabConfig.setUseAuthenticatedEndpoint(false)

gitLabConfig.save()

**Comment by Smasherr** [comment]
Seems it was fixed in https://github.com/jenkinsci/gitlab-plugin/pull/866

**Comment by reinholdfuereder** [comment]
> Seems it was fixed in #866

And released (in GitHub) :-)
... but unfortunately still not picked up by Jenkins plugins updates => #1027 ;-(

**Comment by reinholdfuereder** [comment]
#1027 was resolved and the new release is also picked up and this "useAuthenticatedEndpoint" flag works like a charm :-)
=> @omehegan Thanks again! I think this issue can be resolved as fixed...
